export default {
    'LISTENING_TO_QUESTIONS': 'LISTENING_TO_QUESTIONS',
    'ANSWERING_QUESTION': 'ANSWERING_QUESTION',
    'ASKING_QUESTION': 'ASKING_QUESTION',
    QUESTIONS: {
        ANSWER_YES_NO: 'ANSWER_YES_NO',
        NEXT_QUESTION_YES_NO: 'NEXT_YES_NO',
        NEXT_ANSWER_YES_NO: 'ANSWER_NEXT_YES_NO'
    }
}