export const POLLY_VOICES = [
    {
        lang: `en-US`,
        language: `English`,
        country: 'US',
        gender: `man`,
        name: `Joey`,
    },
    {
        lang: `en-US`,
        language: `English`,
        country: 'US',
        gender: `man`,
        name: `Justin`,
    },
    {
        lang: `en-US`,
        language: `English`,
        country: 'US',
        gender: `man`,
        name: `Matthew`,
    },
    {
        lang: `en-US`,
        language: `English`,
        country: 'US',
        gender: `woman`,
        name: `Ivy`,
    },
    {
        lang: `en-US`,
        language: `English`,
        country: 'US',
        gender: `woman`,
        name: `Joanna`,
    },
    {
        lang: `en-US`,
        language: `English`,
        country: 'US',
        gender: `woman`,
        name: `Kendra`,
    },
    {
        lang: `en-US`,
        language: `English`,
        country: 'US',
        gender: `woman`,
        name: `Kimberly`,
    },
    {
        lang: `en-US`,
        language: `English`,
        country: 'US',
        gender: `woman`,
        name: `Salli`,
    },
    {
        lang: `en-IN`,
        language: `English`,
        country: `India`,
        gender: `woman`,
        name: `Aditi`,
    },
    {
        lang: `en-IN`,
        language: `English`,
        country: `India`,
        gender: `woman`,
        name: `Raveena`,
    },
    {
        lang: `en-GB`,
        language: `English`,
        country: `England`,
        gender: `woman`,
        name: `Amy`,
    },
    {
        lang: `en-GB`,
        language: `English`,
        country: `England`,
        gender: `woman`,
        name: `Emma`,
    },
    {
        lang: `en-GB`,
        language: `English`,
        country: `England`,
        gender: `man`,
        name: `Brian`,
    },
    {
        lang: `en-AU`,
        language: `English`,
        country: `Australia`,
        gender: `woman`,
        name: `Nicole`,
    },
    {
        lang: `en-AU`,
        language: `English`,
        country: `Australia`,
        gender: `man`,
        name: `Russel`,
    },
]